/*
 * Copyright (C) 2026 Manabitan Authors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

import {describe, expect, test} from 'vitest';
import {hashTermKeyByteRange, hashTermKeyBytes, hashTermKeyBytesBulk} from '../ext/js/dictionary/term-key-hash.js';

/**
 * @param {number} length
 * @returns {Uint8Array}
 */
function createBytes(length) {
    return Uint8Array.from({length}, (_, i) => (Math.imul(i, 131) + (i >>> 8)) & 255);
}

describe('bulk persisted-index XXH32', () => {
    test.each([false, true])('matches scalar hashing for every short length and alignment (shared=%s)', (shared) => {
        const storage = shared ? new SharedArrayBuffer(1032) : new ArrayBuffer(1032);
        const whole = new Uint8Array(storage);
        whole.set(createBytes(whole.length));
        const before = Uint8Array.from(whole);
        for (let offset = 0; offset < 8; ++offset) {
            for (let length = 0; length <= 1024; ++length) {
                const view = whole.subarray(offset, offset + length);
                expect(hashTermKeyBytesBulk(view)).toBe(hashTermKeyBytes(view));
                expect(hashTermKeyBytesBulk(view)).toBe(hashTermKeyByteRange(whole, offset, offset + length));
            }
        }
        expect(whole).toStrictEqual(before);
    });

    test.each([4095, 4096, 4097, 65535, 65536, 65537, 1048573, 1048576, 1048579])('preserves index checksums for %i bytes and all word tails', (length) => {
        const source = createBytes(length + 32);
        for (let offset = 0; offset < 8; ++offset) {
            for (let tail = 0; tail < 16; ++tail) {
                const view = source.subarray(offset, offset + length + tail);
                expect(hashTermKeyBytesBulk(view)).toBe(hashTermKeyBytes(view));
            }
        }
    });

    test('hashes shared WASM views before and after memory growth', () => {
        const memory = new WebAssembly.Memory({initial: 1, maximum: 2, shared: true});
        const source = new Uint8Array(memory.buffer, 3, 65530);
        source.set(createBytes(source.length));
        const expected = hashTermKeyBytes(source);
        expect(hashTermKeyBytesBulk(source)).toBe(expected);
        memory.grow(1);
        expect(hashTermKeyBytesBulk(source)).toBe(expected);
        const grown = new Uint8Array(memory.buffer, 3, 100003);
        grown.set(createBytes(grown.length));
        expect(hashTermKeyBytesBulk(grown)).toBe(hashTermKeyBytes(grown));
    });

    test('matches the native XXH32 oracle with the persisted seed', () => {
        // Generated by libxxhash XXH32(bytes, length, 0x811c9dc5), not by either
        // JavaScript implementation. The byte pattern is defined above.
        const vectors = [
            [0, 0x6a7ec0f8],
            [1, 0x87862717],
            [3, 0x68624aa0],
            [4, 0x176a88a5],
            [7, 0x98959cc3],
            [8, 0x63605c04],
            [15, 0x97a56b01],
            [16, 0xcbba3b01],
            [17, 0xe21930d5],
            [31, 0xda50e52b],
            [32, 0x18d89d90],
            [33, 0xbfbd7d17],
            [255, 0x0ee1e006],
            [256, 0x6dbd9522],
            [257, 0x4341e322],
            [4095, 0xd42b482b],
            [4096, 0x0b8ba369],
            [4097, 0x1aaccac1],
            [65535, 0x744ae86c],
            [65536, 0x9d3204ed],
            [1048579, 0x3092157d],
        ];
        for (const [length, expected] of vectors) {
            expect(hashTermKeyBytesBulk(createBytes(length))).toBe(expected);
        }
    });
});
