/*
 * Copyright (C) 2026  Manabitan authors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */


import {createHash} from 'node:crypto';
import {describe, expect, test} from 'vitest';
import {hashPairToHex, hashTermEntryContentBytes, hashTermEntryContentBytesPair} from '../ext/js/dictionary/term-entry-content-hash.js';

/**
 * Golden digest generated by the unchanged hash implementation at
 * 78d8d0b118ca3e4e2d52694aefb11fe9ec43d2c5. Covers every short-path threshold,
 * every four-byte tail and sixteen-byte stripe, plus unaligned backing views.
 * @param {boolean} shared
 * @returns {string}
 */
function corpusDigest(shared) {
    const digest = createHash('sha256');
    for (let length = 0; length < 4096; ++length) {
        for (const offset of [0, 1, 3, 7, 17]) {
            const buffer = shared ? new SharedArrayBuffer(offset + length + 19) : new ArrayBuffer(offset + length + 19);
            const source = new Uint8Array(buffer);
            for (let i = 0; i < source.length; ++i) { source[i] = (i * 73 + (i >>> 2) + length * 11) & 0xff; }
            const bytes = source.subarray(offset, offset + length);
            const pair = hashTermEntryContentBytesPair(bytes);
            const value = hashPairToHex(...pair);
            if (hashTermEntryContentBytes(bytes) !== value) { throw new Error('Pair and string hash disagree'); }
            digest.update(value);
        }
    }
    return digest.digest('hex');
}

describe('term content persistent hash identity', () => {
    test.each([false, true])('matches the baseline corpus (shared=%s)', (shared) => {
        expect(corpusDigest(shared)).toBe('7a629ebc8791ccc2247dc4ff9578a6411ca5d8e505821bee6073624e5f080b7a');
    });

    test('does not include bytes outside a subview', () => {
        const source = new Uint8Array(1024).fill(71);
        const subview = source.subarray(31, 900);
        const expected = hashTermEntryContentBytes(Uint8Array.from(subview));
        expect(hashTermEntryContentBytes(subview)).toBe(expected);
        source.fill(0, 0, 31);
        source.fill(255, 900);
        expect(hashTermEntryContentBytes(subview)).toBe(expected);
    });
});
