name: Benchmarks (Manual)

on:
  workflow_dispatch:

jobs:
  bench:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup

      - name: Run Benchmarks
        continue-on-error: true
        uses: CodSpeedHQ/action@63ae6025a0ffee97d7736a37c9192dbd6ed4e75f # v3.2
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: npm run bench
